[package]
name = "system_snapshot_server"
version = "0.1.0"
authors = ["Abhijat Malviya <malviya.abhijat@gmail.com>"]

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"